Fixed document selector for navbar
chingu-voyages/v40-toucans-team-01 pull request #19
Opened 2022-08-24 23:40 UTC by Tanya-design93

Changed the selector from root to navbar

2022-08-25 19:03 UTC, pamify requested changes
This Navbar.jsx file isn't needed.  All of our components should be rendered in App.jsx

2022-08-26 00:17 UTC, Tanya-design93 commented
Fixed all issues in both PRs in this one PR. I will close the other PR.

2022-08-26 20:12 UTC, pamify approved these changes

2022-08-26 20:13 UTC, KeishaShanice approved these changes

2022-08-26 20:13 UTC, merged